# fly.toml app configuration file generated for notes-api-icy-pond-1313 on 2024-12-23T13:31:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "practice-note-remix-app"
primary_region = "ord"

[build]
  dockerfile = "docker/server.Dockerfile"

[deploy]
  strategy = "rolling"
  release_command = "bun run db:migrate"

[env]
  HOST = "0.0.0.0"
  PORT = "8000"
  DATABASE_CONNECTION_RETRIES = "5"
  DATABASE_CONNECTION_RETRY_DELAY = "5"
  NODE_ENV = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    port = 8000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "data"
  destination = "/data"
