services:
  - type: web
    name: api
    env: docker
    rootDir: apps/server
    region: oregon # Change this to your preferred region
    healthCheckPath: /health
    dockerfilePath: ../../Dockerfile # Path relative to rootDir
    buildCommand: docker build -t api ../../ # Build from monorepo root
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # This will be set manually in the dashboard
    preDeployCommand: bun run db:migrate && bun run db:push
    buildFilter:
      paths:
        - apps/server/** # Changed to absolute path from monorepo root
        - packages/types/** # Changed to absolute path from monorepo root
      ignoredPaths:
        - apps/server/**/*.test.ts
        - apps/server/**/*.spec.ts
        - apps/server/**/README.md
