services:
  - type: web
    name: api
    env: docker
    rootDir: apps/server
    region: oregon # Change this to your preferred region
    healthCheckPath: /health
    dockerfilePath: Dockerfile # Path relative to rootDir
    docker:
      context: . # Context relative to rootDir
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # This will be set manually in the dashboard
    preDeployCommand: bun run db:migrate && bun run db:push # Run migrations before deployment
    buildFilter:
      paths:
        - ./** # All files in server directory
        - ../../packages/types/** # Shared types
      ignoredPaths:
        - ./**/*.test.ts
        - ./**/*.spec.ts
        - ./**/README.md
