services:
  frontend:
    build:
      context: ../.. # Root of monorepo
      dockerfile: apps/remix-frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
